name: MaggieMacnab
favicon: null
layout_spectrum: 0.91299
typography_spectrum: 0.7365126486402005
title: Maggie Macnab
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#896a52'
    - '#dfe3eb'
    - '#1c1f19'
    - '#c2c6ce'
  brandStrength: 0.4083287126850337
  lightness: 0.5316611321177334
  saturation: 0.8945187795907259
  rhythmicContrast: 0.6389346329960972
purpose: []
